/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petcare.view;

import petcare.model.NhanVien;
import java.sql.Connection;
import petcare.control.MyMSSQLControl;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import petcare.control.GlobalValues;

/**
 *
 * @author ngoc
 */
public class QLNhanVien extends javax.swing.JFrame {

    static DefaultTableModel dtmnv = new DefaultTableModel();
    static main m;
    static NhanVien nv;

    /**
     * Creates new form qlnhanvien
     */
    public QLNhanVien(main m) {
        this.m = m;
        this.m = m;
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(QLNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        getContentPane().setBackground(GlobalValues.formBackgroundColor);
        this.setLocationRelativeTo(null);
        customUI();
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icondn.png")));
        loaddata();
        tblNhanVien.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (tblNhanVien.getSelectedRow() >= 0) {
                    String manv = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 0).toString();
                    String tennv = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 1).toString();
                    String gtinh = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 2).toString();
                    String diachi = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 3).toString();
                    String sdt = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 4).toString();
                    String email = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 5).toString();
                    String cmnd = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 6).toString();
                    String chucvu = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 7).toString();
                    boolean nmk = Boolean.parseBoolean(tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 8).toString());
                    int mcv = Integer.parseInt(tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 9).toString());
                    String pw = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 10).toString();
                    nv = new NhanVien(manv, tennv, gtinh, diachi, sdt, email, cmnd, chucvu, nmk, mcv, pw);

                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        pnSearch = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnBacK = new javax.swing.JButton();
        pnAction = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý nhân viên");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1366, 700));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DANH SÁCH NHÂN VIÊN");

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
            }
        ));
        tblNhanVien.setGridColor(new java.awt.Color(255, 255, 255));
        tblNhanVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(tblNhanVien);

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnBacK.setText("Trở lại");
        btnBacK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnSearchLayout = new javax.swing.GroupLayout(pnSearch);
        pnSearch.setLayout(pnSearchLayout);
        pnSearchLayout.setHorizontalGroup(
            pnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addContainerGap())
            .addGroup(pnSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBacK, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnSearchLayout.setVerticalGroup(
            pnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBacK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnAction.setToolTipText("");

        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnActionLayout = new javax.swing.GroupLayout(pnAction);
        pnAction.setLayout(pnActionLayout);
        pnActionLayout.setHorizontalGroup(
            pnActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnActionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnActionLayout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnActionLayout.setVerticalGroup(
            pnActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnActionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEdit)
                        .addComponent(btnAdd)))
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                        .addComponent(pnAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static DefaultTableModel getDtmnv() {
        return dtmnv;
    }

    public static void setDtmnv(DefaultTableModel dtmnv) {
        QLNhanVien.dtmnv = dtmnv;
    }

    public static main getM() {
        return m;
    }

    public static void setM(main m) {
        QLNhanVien.m = m;
    }

    public static NhanVien getNv() {
        return nv;
    }

    public static void setNv(NhanVien nv) {
        QLNhanVien.nv = nv;
    }

    public void loaddata() {
        Connection conn = null;
        Statement stt = null;
        ResultSet rs = null;
        dtmnv.setRowCount(0);
        // trươc khi ket noi fail add thu vien jdbc42.rar
        try {
            conn = MyMSSQLControl.getConnect();
            if (conn == null) {
                JOptionPane.showMessageDialog(rootPane, "lỗi kết nối");
            }
            stt = conn.createStatement();
            String sql = "select * from NHANVIEN";
            rs = stt.executeQuery(sql);
            ResultSetMetaData md = rs.getMetaData();
            Vector row;
            Vector colum = new Vector();
            int number = md.getColumnCount();
            // LAY TEN TUNG COLLUMN name (ROW 1)
            for (int i = 1; i <= number; i++) {
                colum.add(md.getColumnName(i));
                //System.out.println(md.getColumnName(i));
                dtmnv.setColumnIdentifiers(colum);

            }
            ;
            tblNhanVien.setModel(dtmnv);

            // LEN DU LIEU TUNG ROW
            while (rs.next()) {
                row = new Vector();
                //System.out.println("MACD: "+ rs.getString(1)+ " TENCD: "+rs.getString(2));
                row.addElement(rs.getString(1));
                row.addElement(rs.getString(2));
                row.addElement(rs.getString(3));
                row.addElement(rs.getString(4));
                row.addElement(rs.getString(5));
                row.addElement(rs.getString(6));
                row.addElement(rs.getString(7));
                row.addElement(rs.getString(8));
                row.addElement(rs.getBoolean(9));
                row.addElement(rs.getInt(10));
                row.addElement(rs.getString(11));
                dtmnv.addRow(row);

            }

            tblNhanVien.setModel(dtmnv);
            customTableUI();
            tblNhanVien.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {  // DUA DU LIEU VO 2 O TEXT FIELD TUONG UNG
                    if (tblNhanVien.getSelectedRow() >= 0) {
                        String manv = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 0).toString();
                        String tennv = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 1).toString();
                        String gtinh = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 2).toString();
                        String diachi = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 3).toString();
                        String sdt = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 4).toString();
                        String email = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 5).toString();
                        String cmnd = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 6).toString();
                        String chucvu = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 7).toString();
                        boolean nmk = Boolean.parseBoolean(tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 8).toString());
                        int mcv = Integer.parseInt(tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 9).toString());
                        String pw = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 10).toString();
                        nv = new NhanVien(manv, tennv, gtinh, diachi, sdt, email, cmnd, chucvu, nmk, mcv, pw);
                    }

                }

            });

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "loi ket nối");

        }
    }
    private void customTableUI(){
        tblNhanVien.getColumnModel().getColumn(0).setPreferredWidth(20);
        tblNhanVien.getColumnModel().getColumn(1).setPreferredWidth(50);
        tblNhanVien.getColumnModel().getColumn(2).setPreferredWidth(5);
        tblNhanVien.getColumnModel().getColumn(3).setPreferredWidth(150);
        tblNhanVien.getColumnModel().getColumn(4).setPreferredWidth(40);
        tblNhanVien.getColumnModel().getColumn(5).setPreferredWidth(50);
        tblNhanVien.getColumnModel().getColumn(6).setPreferredWidth(40);
        tblNhanVien.getColumnModel().getColumn(7).setPreferredWidth(20);
        tblNhanVien.getColumnModel().getColumn(8).setPreferredWidth(5);
        tblNhanVien.getColumnModel().getColumn(9).setPreferredWidth(5);
        tblNhanVien.getColumnModel().getColumn(10).setPreferredWidth(40);
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // xu ly them thu cung

        XLNhanVien xlnv = new XLNhanVien(this, 0);// o tuc la dang them
        xlnv.setVisible(true);
        loaddata();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBacKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacKActionPerformed
        this.dispose();
        m.setVisible(true);
    }//GEN-LAST:event_btnBacKActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // tim kiếm

        boolean kt = false;
        for (int i = 0; i < tblNhanVien.getRowCount(); i++) {
            for (int j = 0; j < tblNhanVien.getColumnCount(); j++) {
                kt = true;
                if (txtSearch.getText().equals(tblNhanVien.getValueAt(i, j).toString())) {
                    tblNhanVien.setCellSelectionEnabled(true);
                    tblNhanVien.changeSelection(i, j, false, false);
                    tblNhanVien.requestFocus();
                }
            }
        }
        if (kt == false) {
            JOptionPane.showMessageDialog(this, "Không có thông tin nhân viên cần tìm");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // sửa thông tin thú cưng nhưng không đươc sữa các khóa

        XLNhanVien xlnv = new XLNhanVien(this, 1);// o tuc la dang them
        xlnv.setVisible(true);
        loaddata();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //xoa khach hang
        Connection conn = null;
        try {
            conn = MyMSSQLControl.getConnect();
            if (conn == null) {
                JOptionPane.showMessageDialog(rootPane, "lỗi kết nối");
            }
            String sql = "delete NHANVIEN where MANV=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 0).toString());
            int a = ps.executeUpdate();
            if (a > 0) {
                //JOptionPane.showConfirmDialog(this, "them thanh cong");
                // JOptionPane.showMessageDialog(this, "Xóa thành công");
                dtmnv.setRowCount(0);
                loaddata();
            }
            // else JOptionPane.showMessageDialog(rootPane, "Xóa không thành công");
        } catch (Exception e) {
            // JOptionPane.showMessageDialog(rootPane, "Xóa không thành công");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        // tim kiem bang nut enter
        String cm = evt.getActionCommand();
        if (cm != null) {
            boolean kt = false;
            for (int i = 0; i < tblNhanVien.getRowCount(); i++) {
                for (int j = 0; j < tblNhanVien.getColumnCount(); j++) {
                    kt = true;
                    if (txtSearch.getText().equals(tblNhanVien.getValueAt(i, j).toString())) {
                        tblNhanVien.setCellSelectionEnabled(true);
                        tblNhanVien.changeSelection(i, j, false, false);
                        tblNhanVien.requestFocus();
                    }
                }
            }
            if (kt == false) {
                JOptionPane.showMessageDialog(this, "Không có thông tin nhân viên cần tìm");
            }
        }
    }//GEN-LAST:event_txtSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNhanVien(m).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBacK;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnAction;
    private javax.swing.JPanel pnSearch;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void customUI() {
        pnAction.setBackground(GlobalValues.formBackgroundColor);
        pnSearch.setBackground(GlobalValues.formBackgroundColor);
    }
}
