/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petcare.view;

import java.sql.Connection;
import petcare.model.Thuoc;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import petcare.control.GlobalValues;
import petcare.control.MyMSSQLControl;

/**
 *
 * @author ngoc
 */
public class QLThuoc extends javax.swing.JFrame {
static DefaultTableModel dtmt = new DefaultTableModel();
    static main m;
    static Thuoc th;
    /**
     * Creates new form qlthuoc
     */
    public QLThuoc(main m) {
        this.m=m;
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(QLThuoc.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        getContentPane().setBackground(GlobalValues.formBackgroundColor);
        this.setLocationRelativeTo(null);
        customUI();
        loaddata();
        tblThuoc.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {  
                   if(tblThuoc.getSelectedRow()>=0)
                   {
                       String mat = tblThuoc.getValueAt(tblThuoc.getSelectedRow(), 0).toString();
                       String tent = tblThuoc.getValueAt(tblThuoc.getSelectedRow(), 1).toString();
                       float gia = Float.parseFloat(tblThuoc.getValueAt(tblThuoc.getSelectedRow(), 2).toString());
                       Date hsd = Date.valueOf(tblThuoc.getValueAt(tblThuoc.getSelectedRow(), 3).toString());
                       String cdung = tblThuoc.getValueAt(tblThuoc.getSelectedRow(), 4).toString();
                       th = new Thuoc(mat,tent,gia,hsd,cdung);
                       
                   }
                       
           
                }
                 });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThuoc = new javax.swing.JTable();
        pnSearch = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        pnAction = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý thuốc");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1366, 700));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DANH SÁCH THUỐC");

        tblThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblThuoc.setGridColor(new java.awt.Color(255, 255, 255));
        tblThuoc.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(tblThuoc);

        pnSearch.setToolTipText("");

        btnBack.setText("Trở lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnSearchLayout = new javax.swing.GroupLayout(pnSearch);
        pnSearch.setLayout(pnSearchLayout);
        pnSearchLayout.setHorizontalGroup(
            pnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnSearchLayout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnSearchLayout.setVerticalGroup(
            pnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap())
        );

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnActionLayout = new javax.swing.GroupLayout(pnAction);
        pnAction.setLayout(pnActionLayout);
        pnActionLayout.setHorizontalGroup(
            pnActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnActionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnActionLayout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnActionLayout.setVerticalGroup(
            pnActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnActionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEdit)
                        .addComponent(btnAdd)))
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(pnAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(330, 330, 330))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pnAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static DefaultTableModel getDtmt() {
        return dtmt;
    }

    public static void setDtmt(DefaultTableModel dtmt) {
        QLThuoc.dtmt = dtmt;
    }

    public static main getM() {
        return m;
    }

    public static void setM(main m) {
        QLThuoc.m = m;
    }

    public static Thuoc getT() {
        return th;
    }

    public static void setT(Thuoc t) {
        QLThuoc.th = t;
    }

    public JTable getJtt() {
        return tblThuoc;
    }

    public void setJtt(JTable jtt) {
        this.tblThuoc = jtt;
    }
    
    public void loaddata()
    {
        Connection conn =null;
        Statement stt=null;
        ResultSet rs= null;
        dtmt.setRowCount(0);
        try
        {
            conn=MyMSSQLControl.getConnect();
            if(conn==null)
            {
                JOptionPane.showMessageDialog(rootPane, "lỗi kết nối");
            }
            stt=conn.createStatement();
            String sql = "select * from THUOC";
            rs=stt.executeQuery(sql);
            ResultSetMetaData md = rs.getMetaData();
            Vector row;
            Vector colum= new Vector();
            int number = md.getColumnCount();
             // LAY TEN TUNG COLLUMN name (ROW 1)
            for (int i=1;i<=number;i++)
            {
                colum.add(md.getColumnName(i));
                //System.out.println(md.getColumnName(i));
                dtmt.setColumnIdentifiers(colum);
                
            }
            
            tblThuoc.setModel(dtmt);

             // LEN DU LIEU TUNG ROW
            while(rs.next())
            {
                row= new Vector();
                 //System.out.println("MACD: "+ rs.getString(1)+ " TENCD: "+rs.getString(2));
                row.addElement(rs.getString(1));
                row.addElement(rs.getString(2));
                row.addElement(rs.getFloat(3));
                row.addElement(rs.getDate(4));
                row.addElement(rs.getString(5));
                dtmt.addRow(row);
                
            }
            
            tblThuoc.setModel(dtmt);
            customTableUI();
            tblThuoc.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {  // DUA DU LIEU VO 2 O TEXT FIELD TUONG UNG
                   if(tblThuoc.getSelectedRow()>=0)
                   {
                       String mat = tblThuoc.getValueAt(tblThuoc.getSelectedRow(), 0).toString();
                       String tent = tblThuoc.getValueAt(tblThuoc.getSelectedRow(), 1).toString();
                       float gia = Float.parseFloat(tblThuoc.getValueAt(tblThuoc.getSelectedRow(), 2).toString());
                       Date hsd = Date.valueOf(tblThuoc.getValueAt(tblThuoc.getSelectedRow(), 3).toString());
                       String cdung = tblThuoc.getValueAt(tblThuoc.getSelectedRow(), 4).toString();
                       
                       th = new Thuoc(mat,tent,gia,hsd,cdung);
                   }
                       
           
                }
              
        });
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "loi ket nối");
            
        }
    }   
    private void customTableUI(){
        tblThuoc.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblThuoc.getColumnModel().getColumn(1).setPreferredWidth(50);
        tblThuoc.getColumnModel().getColumn(2).setPreferredWidth(50);
        tblThuoc.getColumnModel().getColumn(3).setPreferredWidth(50);
        tblThuoc.getColumnModel().getColumn(4).setPreferredWidth(300);
    }
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //xoa khach hang
        Connection conn =null;
        try
        {
            conn=MyMSSQLControl.getConnect();
            if(conn==null)
            {
                JOptionPane.showMessageDialog(rootPane, "lỗi kết nối");
            }
            String sql = "delete THUOC where MATH=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1,tblThuoc.getValueAt(tblThuoc.getSelectedRow(),0).toString());
            int a= ps.executeUpdate();
            if(a>0)
            {
                //JOptionPane.showConfirmDialog(this, "them thanh cong");
                // JOptionPane.showMessageDialog(this, "Xóa thành công");
                dtmt.setRowCount(0);
                loaddata();
            }
            // else JOptionPane.showMessageDialog(rootPane, "Xóa không thành công");
        }catch(Exception e)
        {
            // JOptionPane.showMessageDialog(rootPane, "Xóa không thành công");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // xu ly them thu cung
        XLThuoc xlt = new XLThuoc(this,0);// o tuc la dang them
        xlt.setVisible(true);
        loaddata();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        m.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // tim kiếm

        boolean kt= false;
        for(int i=0;i<tblThuoc.getRowCount();i++)
        {
            for(int j=0;j<tblThuoc.getColumnCount();j++)
            {
                kt=true;
                if(txtSearch.getText().equals(tblThuoc.getValueAt(i, j).toString()))
                {
                    tblThuoc.setCellSelectionEnabled(true);
                    tblThuoc.changeSelection(i,j, false, false);
                    tblThuoc.requestFocus();
                }
            }
        }
        if(kt==false) JOptionPane.showMessageDialog(this, "Không có thông tin thuốc cần tìm");
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        // tim kiem bang nut enter
        String cm = evt.getActionCommand();
        if(cm!=null)
        {
            boolean kt= false;
            for(int i=0;i<tblThuoc.getRowCount();i++)
            {
                for(int j=0;j<tblThuoc.getColumnCount();j++)
                {
                    kt=true;
                    if(txtSearch.getText().equals(tblThuoc.getValueAt(i, j).toString()))
                    {
                        tblThuoc.setCellSelectionEnabled(true);
                        tblThuoc.changeSelection(i,j, false, false);
                        tblThuoc.requestFocus();
                    }
                }
            }
            if(kt==false) JOptionPane.showMessageDialog(this, "Không có thông tin thuốc cần tìm");
        }
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // sửa thông tin thú cưng nhưng không đươc sữa các khóa

        XLThuoc xlt = new XLThuoc(this,1);// o tuc la dang them
        xlt.setVisible(true);
        loaddata();
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLThuoc(m).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnAction;
    private javax.swing.JPanel pnSearch;
    private javax.swing.JTable tblThuoc;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void customUI() {
        pnAction.setBackground(GlobalValues.formBackgroundColor);
        pnSearch.setBackground(GlobalValues.formBackgroundColor);
    }
}
