/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petcare.view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import petcare.control.GlobalValues;
import petcare.control.MyMSSQLControl;

/**
 *
 * @author ngoc
 */
public class XLThuCung extends javax.swing.JDialog {

    static int chucnang;
    static QLThuCung qltc;
    static int soluong;
    static boolean ketthuc = false;
    static QLKhachHang qlkh;

    /**
     * Creates new form xlthucung
     */
    public XLThuCung(QLThuCung qltc, QLKhachHang qlkh, int chucnang) { // 0 them , 1 sua ,2 xoa
        this.chucnang = chucnang;
        this.qltc = qltc;
        this.qlkh = qlkh;
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(XLThuCung.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        getContentPane().setBackground(GlobalValues.formBackgroundColor);
        this.setLocationRelativeTo(null);
        this.setModal(true);
        if (this.chucnang == 1) {
            btnMaTC.setText(qltc.tc.getMatc());
            txtMaKH.setText(qltc.tc.getMakh());
            // viec sua thong tin thu cung se khong cho phep sua cac gia trị khoa
            btnMaTC.setEnabled(false);
            // jtfmkh.setEnabled(false);
            txtTenTC.setText(qltc.tc.getTentc());
            txtTuoi.setText(String.valueOf(qltc.tc.getTuoi()));
            txtChungLoai.setText(qltc.tc.getcLoai());
            txtTinhTrang.setText(qltc.tc.gettTrang());
        }
        if (this.chucnang == 2) {
            txtMaKH.setText(qlkh.kh.getMakh());
            txtMaKH.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();
        btnDiscard = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtTinhTrang = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnMaTC = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTenTC = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTuoi = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtChungLoai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông tin thú cưng");
        setLocationByPlatform(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("THÔNG TIN THÚ CƯNG");

        btnDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petcare/view/drawable/ic_save_black_18dp.png"))); // NOI18N
        btnDone.setText("Xong");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        btnDiscard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petcare/view/drawable/ic_close_black_18dp.png"))); // NOI18N
        btnDiscard.setText("Hủy");
        btnDiscard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscardActionPerformed(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petcare/view/drawable/ic_navigate_next_black_18dp.png"))); // NOI18N
        btnNext.setText("Tiếp");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 153)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Tình trạng");

        txtTinhTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTinhTrangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(49, 49, 49)
                .addComponent(txtTinhTrang, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 153)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Mã thú cưng");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnMaTC, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnMaTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 153)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Mã khách hàng");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 153)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tên thú cưng");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(19, 19, 19)
                .addComponent(txtTenTC, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 153)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Tuổi");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 153)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Chủng loại");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(49, 49, 49)
                .addComponent(txtChungLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtChungLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petcare/view/drawable/ic_pet_add.png"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 153)));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnDone, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDiscard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 62, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel15, jPanel16, jPanel17, jPanel18, jPanel19, jPanel20});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDiscard)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static QLThuCung getQltc() {
        return qltc;
    }

    public static void setQltc(QLThuCung qltc) {
        XLThuCung.qltc = qltc;
    }

    public static int getSoluong() {
        return soluong;
    }

    public static void setSoluong(int soluong) {
        XLThuCung.soluong = soluong;
    }

    public static QLKhachHang getQlkh() {
        return qlkh;
    }

    public static void setQlkh(QLKhachHang qlkh) {
        XLThuCung.qlkh = qlkh;
    }

    public static int getChucnang() {
        return chucnang;
    }

    public static void setChucnang(int chucnang) {
        XLThuCung.chucnang = chucnang;
    }

    public void xuly() {
        Connection conn = null;
        if (this.chucnang == 0) // them thu cung khác cua 1 khach hang da co trong he thong
        {
            ketthuc = true;
            try {
                boolean KT = true;
                conn = MyMSSQLControl.getConnect();
                if (conn == null) {
                    JOptionPane.showMessageDialog(rootPane, "Lỗi kết nối");
                }
                String sql = "insert into THUCUNG values(?,?,?,?,?,?)";
                PreparedStatement ps = conn.prepareStatement(sql);// DUNG DC TRONG CA TRUY CAN CO DOI SO VA KHONG DOI SO (?)
                ps.setString(1, btnMaTC.getText());
                ps.setString(2, txtMaKH.getText());
                ps.setString(3, txtTenTC.getText());
                // bat exception loi nhap sai thong tin tuoi
                try {
                    if (Integer.parseInt(txtTuoi.getText()) <= 0) {
                        KT = false;
                        JOptionPane.showMessageDialog(this, "Tuối phải lớn hơn 0");
                    }
                    ps.setInt(4, Integer.parseInt(txtTuoi.getText()));
                } catch (Exception e) {
                    KT = false;
                    JOptionPane.showMessageDialog(this, "Số tuối nhập vào sai định dạng");
                }

                ps.setString(5, txtChungLoai.getText());
                ps.setString(6, txtTinhTrang.getText());
                // kiem tra xem thu cung them vao la cua ma khach hang da co trong he thong hay chưa
                boolean kt = false; // xac dinh khach hang co tôn tai trong dskh chua
                int indexkh = 0;// dung de luu lai vi tri khach hang da ton tai trong dskh
                for (int i = 0; i < this.qltc.m.getDskh().size(); i++) {
                    if (qltc.m.getDskh().get(i).getMakh().equals(txtMaKH.getText())) {
                        kt = true;
                        indexkh = i;
                        // tien hanh cap nhat muc so luong thu cung cua khach hang tai day lun cho do phai tim lan 2
                        qltc.m.getDskh().get(i).setSltc(qltc.m.getDskh().get(i).getSltc() + 1);
                        break;
                    }
                }
                if (kt == true && KT == true) {
                    int a = ps.executeUpdate();
                    if (a > 0) {
                        //JOptionPane.showConfirmDialog(this, "them thanh cong");
                        // JOptionPane.showMessageDialog(this, "Them thanh cong");
                        // tien hanh cap nhat so luong thu cung của khach hang do lai
                        // lay cap nhat data KhachHang truoc roi neu sau do neu muon xai csdl thi moi load lai csdl moi tren data nay

                        // cap nhat so luong thu cung cua khach hang tren database
                        String sql1 = "update KHACHHANG set SOLUONG=? where MAKH=?";
                        PreparedStatement ps1 = conn.prepareStatement(sql1);
                        ps1.setInt(1, qltc.m.getDskh().get(indexkh).getSltc());
                        ps1.setString(2, txtMaKH.getText());
                        int b = ps1.executeUpdate();
                        if (b > 0) {
                            //JOptionPane.showConfirmDialog(this, "them thanh cong");
                            // JOptionPane.showMessageDialog(this, "cap nhat khach hang thanh cong");                   
                        }

                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Mã khách hàng chưa có trong danh sách khách hàng");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Lỗi kết nối");
            }

        }

        if (this.chucnang == 1) // chuc nang sua thu cung
        {
            ketthuc = true;
            try {
                boolean kiemtra = true;
                conn = MyMSSQLControl.getConnect();
                if (conn == null) {
                    JOptionPane.showMessageDialog(rootPane, "Lỗi kết nối");
                }
                String sql = "update THUCUNG set MAKH=?, TENTC=?,TUOI=?,CLOAI=?,TTRANG=? where MATC=?";
                PreparedStatement ps = conn.prepareStatement(sql);// DUNG DC TRONG CA TRUY CAN CO DOI SO VA KHONG DOI SO (?)
                ps.setString(6, btnMaTC.getText());
                ps.setString(1, txtMaKH.getText());
                ps.setString(2, txtTenTC.getText());
                // bat exception loi nhap sai thong tin tuoi
                try {
                    if (Integer.parseInt(txtTuoi.getText()) <= 0) {
                        kiemtra = false;
                        JOptionPane.showMessageDialog(this, "Tuối phải lớn hơn 0");
                    }
                    ps.setInt(3, Integer.parseInt(txtTuoi.getText()));
                } catch (Exception e) {
                    kiemtra = false;
                    JOptionPane.showMessageDialog(this, "Số tuối nhập vào sai định dạng");
                }

                ps.setString(4, txtChungLoai.getText());
                ps.setString(5, txtTinhTrang.getText());
                // kiem tra xem thu cung them vao la cua ma khach hang da co trong he thong hay chưa
                boolean kt = false; // xac dinh khach hang co tôn tai trong dskh chua
                boolean KT = false; // kiem tra la sua ma khach hang khac hay khong sua ma khach hang
                int indexkhold = 0;// dung de luu lai vi tri khach hang da ton tai trong dskh
                int indexkhnew = 0;
                for (int i = 0; i < this.qltc.m.getDskh().size(); i++) {
                    // neu sua khach hang -> khach hang khac trong he thong thi cap nhat thong tin 2 khach hang 1 tang 1 giam (so luong tc)

                    if (qltc.m.getDskh().get(i).getMakh().equals(txtMaKH.getText()) && qltc.tc.getMakh().equals(txtMaKH.getText()) == false) {
                        kt = true;
                        for (int j = 0; j < this.qltc.m.getDskh().size(); j++) {
                            if (qltc.tc.getMakh().equals(qltc.m.getDskh().get(j).getMakh())) // tim vi tri khach hang cu de cap nhat
                            {
                                indexkhold = j;
                            }
                        }
                        indexkhnew = i;// vi tri khach hang 
                        // tien hanh cap nhat muc so luong thu cung cua khach hang tai day lun cho do phai tim lan 2
                        qltc.m.getDskh().get(i).setSltc(qltc.m.getDskh().get(i).getSltc() + 1); // so luong tc cua khach hang moi tang len
                        qltc.m.getDskh().get(indexkhold).setSltc(qltc.m.getDskh().get(indexkhold).getSltc() - 1); // so luong tc cua khach hang cu giam xuong
                        break;
                    }
                    if (qltc.m.getDskh().get(i).getMakh().equals(txtMaKH.getText()) && qltc.tc.getMakh().equals(txtMaKH.getText())) {
                        kt = true;
                        KT = true;
                    }

                }
                if (kt == true && KT == true && kiemtra == true) {
                    int a = ps.executeUpdate();// tien hanh cap nhat lai csdl
                    if (a > 0) {
                        //JOptionPane.showMessageDialog(this, "Sua thanh cong");
                    }
                    //else JOptionPane.showMessageDialog(this, "Sua khong thanh cong");
                }
                if (kt == true && KT == false && kiemtra == true) {
                    int a = ps.executeUpdate();
                    if (a > 0) {
                        //JOptionPane.showConfirmDialog(this, "them thanh cong");
                        // JOptionPane.showMessageDialog(this, "Sua thanh cong");
                        // tien hanh cap nhat so luong thu cung của khach hang do lai
                        // lay cap nhat data KhachHang truoc roi neu sau do neu muon xai csdl thi moi load lai csdl moi tren data nay

                        // cap nhat so luong thu cung cua khach hang tren database
                        String sql1 = "update KHACHHANG set SOLUONG=? where MAKH=?";
                        PreparedStatement ps1 = conn.prepareStatement(sql1);
                        // cap nhat khach hang moi
                        ps1.setInt(1, qltc.m.getDskh().get(indexkhnew).getSltc());
                        ps1.setString(2, txtMaKH.getText());
                        int b = ps1.executeUpdate();
                        if (b > 0) {
                            //JOptionPane.showConfirmDialog(this, "them thanh cong");
                            // JOptionPane.showMessageDialog(this, "cap nhat khach hang thanh cong");                   
                        }
                        // cap nhat khach hang cu
                        ps1.setInt(1, qltc.m.getDskh().get(indexkhold).getSltc());
                        ps1.setString(2, qltc.m.getDskh().get(indexkhold).getMakh());
                        int c = ps1.executeUpdate();
                        if (c > 0) {

                        }

                    }
                }
                if (kt == false) {
                    JOptionPane.showMessageDialog(this, "Mã khách hàng chưa có trong danh sách khách hàng");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Lỗi kết nối");
            }

        }

        if (this.chucnang == 2) // them n thu cung tu khu vuc quan ly khach hang
        {

            try {
                boolean kt = true;
                conn = MyMSSQLControl.getConnect();
                if (conn == null) {
                    JOptionPane.showMessageDialog(rootPane, "Lỗi kết nối");
                }
                String sql = "insert into THUCUNG values(?,?,?,?,?,?)";
                PreparedStatement ps = conn.prepareStatement(sql);// DUNG DC TRONG CA TRUY CAN CO DOI SO VA KHONG DOI SO (?)
                ps.setString(1, btnMaTC.getText());
                ps.setString(2, qlkh.kh.getMakh());
                ps.setString(3, txtTenTC.getText());
                // bat exception loi nhap sai thong tin tuoi
                try {
                    if (Integer.parseInt(txtTuoi.getText()) <= 0) {
                        kt = false;
                        JOptionPane.showMessageDialog(this, "Tuối phải lớn hơn 0");
                    }
                    ps.setInt(4, Integer.parseInt(txtTuoi.getText()));
                } catch (Exception e) {
                    kt = false;
                    JOptionPane.showMessageDialog(this, "Số tuối nhập vào sai định dạng");
                }

                ps.setString(5, txtChungLoai.getText());
                ps.setString(6, txtTinhTrang.getText());
                // kiem tra xem thu cung them vao la cua ma khach hang da co trong he thong hay chưa

                if (kt == true) {
                    int a = ps.executeUpdate();
                    if (a > 0) {
                        ketthuc = true;
                    }
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Lỗi kết nối");
            }

        }

    }
    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // xu lý nut Xong la them hay sua 

        xuly();

        if (ketthuc == true) {
            this.setVisible(false);
            if (chucnang == 2) {
                qlkh.getDtmkh().setRowCount(0);
                qlkh.setVisible(true);
                qlkh.loaddata();
            } else {
                qltc.getDtmtc().setRowCount(0);
                qltc.setVisible(true);
                qltc.loaddata();
            }

        } else {
            this.setVisible(false);
            soluong = soluong++;
            XLThuCung xltc = new XLThuCung(null, qlkh, 2);
            xltc.setVisible(true);
            xuly();
        }
    }//GEN-LAST:event_btnDoneActionPerformed

    private void btnDiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscardActionPerformed
        this.dispose();
        if (chucnang == 2) {
            qlkh.getDtmkh().setRowCount(0);
            qlkh.setVisible(true);
            qlkh.loaddata();
        } else {
            qltc.getDtmtc().setRowCount(0);
            qltc.setVisible(true);
            qltc.loaddata();
        }
    }//GEN-LAST:event_btnDiscardActionPerformed

    private void txtTinhTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTinhTrangActionPerformed
        // TODO add your handling code here:
        String cm = evt.getActionCommand();
        if (cm != null) {
            xuly();
        }

        this.setVisible(false);
        if (chucnang == 2) {
            qlkh.getDtmkh().setRowCount(0);
            qlkh.setVisible(true);
            qlkh.loaddata();
        } else {
            qltc.getDtmtc().setRowCount(0);
            qltc.setVisible(true);
            qltc.loaddata();
        }
    }//GEN-LAST:event_txtTinhTrangActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // nhap thong tin thu cung tiep theo 
        this.setVisible(false);
        XLThuCung xltc = new XLThuCung(null, qlkh, 2);
        xltc.setVisible(true);
        xuly();
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XLThuCung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XLThuCung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XLThuCung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XLThuCung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XLThuCung(qltc, qlkh, chucnang).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiscard;
    private javax.swing.JButton btnDone;
    private javax.swing.JTextField btnMaTC;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JTextField txtChungLoai;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtTenTC;
    private javax.swing.JTextField txtTinhTrang;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables
}
